### ISSUE TITLE
Add reminder mail if user has signed up but never submitted any solution

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-laboratory#964] opened 2018-03-22 15:51 UTC

**Comment by flbulgarelli** [comment] 2018-04-01 22:25
Fixed in https://github.com/mumuki/mumuki-laboratory/commit/911481e54a693ba2c88c134e7981d83cd2592474

**Comment by flbulgarelli** [comment] 2018-06-11 21:25
Duplicate of #1075

**Closed by flbulgarelli** 2018-06-11 21:25 UTC
