### ISSUE TITLE
Update mumukit-inspection version to support expectations in pt

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-laboratory#966] opened 2018-03-23 15:51 UTC

**Comment by flbulgarelli** [comment] 2018-03-23 17:35
Which expectations are missing?

**Comment by aguspina** [comment] 2018-03-23 17:41
Everyone, because they are not included in the last mumukit-inspection tag.

**Comment by flbulgarelli** [comment] 2018-04-01 22:24
Duplicate of https://github.com/mumuki/mumuki-laboratory/issues/967

**Closed by flbulgarelli** 2018-04-01 22:24 UTC
