### ISSUE TITLE
Show users how many exercises they have answered correctly so far

### ISSUE THREAD

**Issue by lauramangifesta** [mumuki/mumuki-laboratory#969] opened 2018-03-27 15:15 UTC
Users are asking for an easier way to count the exercises. It would be fantastic if we could show them how many exercises they answered correctly. Maybe we could congratulate them for their progress. It could work as a motivation and reduce the uncertainty:
"Congratulations! You have solved X exercises so far. Keep practicing!"

**Comment by flbulgarelli** [comment] 2021-03-05 19:12
Closing as duplicate of #1540

**Closed by flbulgarelli** 2021-03-05 19:12 UTC
